debug: true

zones:
  world: "build"
  pros:
    pos1:
      x: 1
      y: 1
      z: 1
    pos2:
      x: 1
      y: 1
      z: 1
    spawn:
      x: 0
      y: 90
      z: 0

  noobs:
    pos1:
      x: 1
      y: 1
      z: 1
    pos2:
      x: 1
      y: 1
      z: 1
    spawn:
      x: 0
      y: 90
      z: 0